### ISSUE TITLE
Roland V-600UHD / Companion 2.0

### ISSUE THREAD

**Issue by EMiBias** [bitfocus/companion-module-roland-v600uhd#1]
Just a reiteration of my message on the FB group.. 

Had a number of failed attempts to run the Roland V-600uhd with Companion 2.0. Connection was solid, status was good but no results. Closer inspection revealed the obvious. The Roland V-600UHD config file is set to connect to the Roland **V-60HD** and not in fact to the V-600UHD. See attached: 

<img width="1428" alt="Screenshot 2019-12-17 at 09 35 45" src="https://user-images.githubusercontent.com/15999417/70987230-5e372e00-20b7-11ea-8c33-0647dcb57cb1.png">

**Comment by josephdadams** [comment]
@EMiBias when Roland sent me the protocol spec, they said this: “Please note that the commands will be activated in a future update, the current version has them disabled.”

That was in June. Have you done any device updates yet? You may want to reach out to them about having it enabled. I am not a Roland customer or user. I just wrote the module as a kindness to people like you. :)

**Comment by EMiBias** [comment]
Thanks Joseph, unfortunately I only had access to the switcher for one day before the xmas break. There'll be other jobs with it next year but until then I'll have to put it on the back burner. 

It was mentioned in a separate conversation that the firmware was updated last week, but I have no further details on that. I'll go over all details the next chance I get. :|

**Comment by josephdadams** [comment]
Sounds good. When you have access to it, look up the protocol online and try to telnet to the switcher to see if you can control it. I’ll close this issue. Feel free to re open or submit a new one when you have access to the device again and have experienced issues with the Companion module after testing with telnet. Thanks!

**Comment by JeffreyDavidsz** [comment]
@josephdadams can you delete the references in the module to 600UHD model? I know that in November the firmware wasn't ready yet. Just add it back when it's confirmed working?

**Comment by josephdadams** [comment]
This module is only for the 600UHD. Nothing else. So if you don’t want it included, you’ll have to remove it from the core. I don’t yet know if the reason this module didn’t work was user error, module error, or firmware related.

**Comment by JeffreyDavidsz** [comment]
When we put it in the core no problem for someone to test. But if the current state of the switcher doesn't work, better wait. Could you adjust the text in the picture above?

**Comment by josephdadams** [comment]
@JeffreyDavidsz Let me reach out to Roland first and see if they’ve enabled these functions yet before modifying the info box.

**Comment by JeffreyDavidsz** [comment]
Great!

**Comment by EMiBias** [comment]
> This module is only for the 600UHD. Nothing else. So if you don’t want it included, you’ll have to remove it from the core. I don’t yet know if the reason this module didn’t work was user error, module error, or firmware related.

I can assure you that it wasn't user error, what I can't guarantee is whether the firmware is up to date or not. It's unfortunate that I'm not in a position to carry out any further testing in the short term.

**Comment by josephdadams** [comment]
Official word from Roland is that firmware version 1.07 or later is required. They recommend going to 1.10 as it is a significant and recommended update.

**Comment by krocheck** [comment]
@josephdadams  Might be good to drop that in the information block along with the model name update.

**Comment by josephdadams** [comment]
Done
