### ISSUE TITLE
Command not work after upgrading the Roland from 2.04 to 3.01.

### ISSUE THREAD

**Issue by paulstec** [bitfocus/companion-module-roland-v600uhd#11]
Upgraded the roland-v600uhd from 2.04 to 3.01 released this week.
Now the Roland does not respond to the Companion module calls.  Running Companion 3.2.0 with module Roland V-600UHD v2.0.0.

Is there an update to the module that addresses this?

**Comment by paulstec** [comment]
I'm working on 2.0.1 to resolve this issue.

Hopefully, can submit a pull request next week after more testing.

**Comment by paulstec** [comment]
This is fixed in pull request #12.

Roland added a required password in firmware 3.00. 

Support for a password was added by mirroring password support found in another Roland module.  Guess Roland is adding this across their products.

**Comment by josephdadams** [comment]
fixed in #12
