### ISSUE TITLE
Select PST command does not execute

### ISSUE THREAD

**Issue by swampcat** [bitfocus/companion-module-roland-v600uhd#3]
The command "Select PST" fails to execute because the action name is defined in one place in the code as ```select_pst``` and another place as ```select_pvw```. I opened a pull request with the correction for the select statement.

**Comment by josephdadams** [comment]
Looks great. Please add a commit for `package.json` that changes the version number to `1.0.2`.

**Comment by swampcat** [comment]
Done. Thank you.

**Comment by josephdadams** [comment]
merged and updated in core now, thanks!
