### ISSUE TITLE
Does not appear that any of the functions work.

### ISSUE THREAD

**Issue by paulstec** [bitfocus/companion-module-roland-v600uhd#4]
We have many uses for this module if we can understand how to get to work with our configuration.

Initially, testing with the buttons to press DSK or COMPOSITION.  Nothing happens.  (This would be useful.)

Also tried buttons setting PGM to each of the 4 HDMI in settings.  Nothing seems to happen.  Would like to be able to set which of the 1-8 buttons are selected (Red) on the PGM row of the device.

Please let me know if additional information or testing would help.

**Comment by josephdadams** [comment]
Pretty sure your Roland has to be on firmware 2.01 or something. Can you confirm?

**Comment by paulstec** [comment]
Thanks.  Looks like our Roland firmware is 2.00.

Can you confirm what firmware is required?
 (Don’t  want to apply firmware that is too new for the module.  Had issues with ProPresenter that required going back a software release which is ok.  Do not want to be in same situation with firmware.)

Meanwhile I can look at upgrading firmware.

**Comment by josephdadams** [comment]
Sorry but I don't have one of these devices. I just wrote the module as a gift to the community. I'm pretty sure other people use it.

**Comment by paulstec** [comment]
I understand.  My question was more an interest in what firmware version did the vendor add the API support that permitted you to write the module.

Looking at the release notes, there is nothing I recognize as adding the API for Companion or anything else that want's to use it.  Also, do you know where Roland documents the API as that may provide a hint?

A quick check of the Support site indicates the latest firmware is 2.03.  This was released February 2022.

I'll apply this soon and let you know!

**Comment by paulstec** [comment]
The Roland upgraded to 2.03 easily.  However, I still can't tell any difference with the Companion module.

Maybe, I'm not configuring the button correctly.  The DSK and Composition buttons have a push down action of "Push the DSK/Composition button.  However, nothing happens.

When I go to the 600UHD web interface on port 8080, there are many tabs that correspond to values in the device menu.  There are DSK and Composition tabs.  Each has a pull down labeled "Status PGM:" that have On/Off as choices.    

Perhaps that can be set that as a POST in the generic HTTP module, but I'm not sure how to do that.

Another idea is I could post on the Companion user group to see if anyone has it working and would share their configuration.

**Comment by paulstec** [comment]
@josephdadams Can you share some of the Roland API details that were used in the module?

Perhaps that will provide insight to help me understand what the module is doing.  

Also is this something that can be triggered by one of the generic modules?   (TCP, UDP or HTTP)

**Comment by paulstec** [comment]
@josephdadams Roland support was very helpful.  They tried the Companion module with a 600UHD at the latest firmware and did not find that the module worked.

However, he did get it working with the generic TCP module.  Naturally, it's TCP port 8023.  For the Cut function he used the command "cut;" with the command end character "CR-\r (Old MacOS)".

I followed the same pattern and have working buttons for Cut, toggling DSK and toggling Composition.  Then added buttons to set PGM to each of the 8 selections begining with "PGM:0;".

Roland noted the details are on page 53 of the reference guide.  https://rolandus.zendesk.com/attachments/token/IBicIbXB08voJwY8KTuvq4t8N/?name=V-600UHD+-+Reference+Manual+-+e05.pdf

Wish I understood Github and Companion module development enough to submit an update for this module.  Perhaps someday, but not today.

Thanks for your help and guidance.

**Comment by josephdadams** [comment]
The module does not currently send a carriage return but we could try adding that to see if it helps. The commands are the same, I used the reference manual to create it.

**Comment by paulstec** [comment]
Adding a carriage return sounds good.  Please let me know if there is convenient way for me to test the revised module.

A side topic is the labels for "CHOICES_INPUTS" confused me.  I was expecting something like "XPT 1" to "XPT 8".  (See below.)  Granted if the carriage return is added the commands should work.

Thanks again for the exchange.  I appreciate the learning and your patience while I get there.


instance.prototype.CHOICES_INPUTS = [
	{ id: '0', label: 'HDMI / RGB IN 1'},
	{ id: '1', label: 'HDMI IN 2'},
	{ id: '2', label: 'HDMI IN 3'},
	{ id: '3', label: 'HDMI IN 4'},
	{ id: '4', label: 'SDI IN 5'},
	{ id: '5', label: 'SDI IN 6'},
	{ id: '6', label: 'Still 1'},
	{ id: '7', label: 'Still 2 / Pattern Generator'}
]

Item Sent command Response command Parameter
Select PGM channel stxPGM:a; ACK a: 0 (XPT 1) –7 (XPT 8)
Select PST channel stxPST:a; ACK a: 0 (XPT 1) –7 (XPT 8)
Select channel to send to AUX bus stxAUX:a; ACK a: 0 (XPT 1) –7 (XPT 8)

**Comment by josephdadams** [comment]
It now sends crlf with every command. Look for the beta build that references this update and test it out.

**Comment by paulstec** [comment]
The new module that I grabbed does not work.  Based on the generic TCP module, it might need "\r".

CHOICES_END=[
                {id: '',label: 'None'},
                {id: '\n',label: 'LF - \\n<file://n> (Common UNIX/Mac)'},
                {id: '\r\n',label: 'CRLF - \\r\\n<file://r/n> (Common Windows)'},
                {id: '\r',label: 'CR - \\r<file://r> (Old MacOS)'},
                {id: '\x00',label: 'NULL - \\x00<file://x00> (Can happen)'},
                {id: '\n\r',label: 'LFCR - \\n\\r<file://n/r> (Just stupid)'},
        ]

From <https://github.com/bitfocus/companion-module-generic-tcp-udp/blob/master/index.js>
***@***.***

**Comment by josephdadams** [comment]
Can you test with the generic that \r\n doesn’t work?

**Comment by paulstec** [comment]
It might be a while.  FYI: The module tested is "2.2.0 (2.2.0+4187-beta-1e27839a) This build is experimental"

2.2.0 (2.2.0+4187-beta-1e27839a)<https://bitfocus.io/companion/>

**Comment by paulstec** [comment]
The \r and \r\n both work.  Actually, all the end characters work in the generic module.

Generic module: command cut;

Command end character works:
CR-\r (old macOS)

FYI: That was the setting that the tech from Roland verified in his lab.

Command end character also works:
Calf-\r\n (common Windows)



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by josephdadams** [comment]
You’re not sending the stx character at the beginning and the module is. So I guess that could be the issue. I wouldn’t think it would be case sensitive. CUT vs cut.

**Comment by paulstec** [comment]
Agree, the generic TCP module doesn’t look like it sends the stx character.

As for the case of the cut command, case doesn’t seem to matter.  That said, all my other buttons are using upper case.

**Comment by josephdadams** [comment]
I’ll remove stx and publish a new version to the betas.

**Comment by josephdadams** [comment]
pushed version that removes stx.  please test

**Comment by paulstec** [comment]
Success!  The button actions work.  Thank you.
